#include "DiagnosticsService.h"
#include "EndpointPolicy.h"
#include <QDir>
#include <QFile>
#include <QHostInfo>
#include <QCoreApplication>
#include <QMetaObject>
#include <QPointer>
#include <QRegularExpression>
#include <QTcpSocket>
#include <QThreadPool>
#include <QTimer>

namespace {
QString scrub(QString t){static const QRegularExpression re(QStringLiteral("(?i)\\b(?:password|senha|token|psk|pin|key|chave|codigo|código)\\s*[:=]\\s*[^\\s,;]+"));t.replace(re,"[redigido]");return t;}
DiagnosticSeverity aggregate(const QList<DiagnosticCheck>&cs){DiagnosticSeverity r=DiagnosticSeverity::Ok;for(const auto&c:cs){if(c.severity==DiagnosticSeverity::Error)return c.severity;if(c.severity==DiagnosticSeverity::Warning)r=c.severity;}return r;}
DiagnosticsAdapter::FolderProbe folderProbe(QString path){if(path.trimmed().isEmpty())return{false,false,false,"A pasta não foi configurada."};QDir d(path);if(!d.exists())return{false,false,false,"A pasta não existe."};QString p=d.filePath(QStringLiteral(".inputleap-diagnostic-%1.tmp").arg(QUuid::createUuid().toString(QUuid::WithoutBraces)));QFile f(p);if(!f.open(QIODevice::WriteOnly|QIODevice::NewOnly))return{true,false,false,f.errorString()};bool wrote=f.write("diagnostic",10)==10&&f.flush();f.close();bool removed=QFile::remove(p);return{true,wrote&&removed,wrote&&removed,wrote&&removed?"Arquivo temporário exclusivo criado e removido.":"Falha ao concluir/remover o arquivo temporário."};}
}
QString DiagnosticsReport::toPlainText(bool tech)const{QStringList l;for(const auto&c:checks){QString s=c.severity==DiagnosticSeverity::Ok?"OK":c.severity==DiagnosticSeverity::Warning?"Atenção":"Erro";QString x=QStringLiteral("%1: %2 — %3").arg(c.id,s,c.simple);if(tech&&!c.technical.isEmpty())x+="\n  "+c.technical;l<<x;}return l.join('\n');}
class DiagnosticsService::RealAdapter final:public QObject,public DiagnosticsAdapter{
public:explicit RealAdapter(QObject*p):QObject(p){}
 void resolveHost(const QString&h,ResolveCallback cb)override{int id=QHostInfo::lookupHost(h,this,[cb=std::move(cb)](const QHostInfo&i)mutable{QStringList a;for(const auto&x:i.addresses())a<<x.toString();cb({a,i.error()==QHostInfo::NoError?QString():i.errorString()});});lookups_<<id;}
 void probeTcp(const QString&h,quint16 p,int timeout,TcpCallback cb)override{auto*s=new QTcpSocket(this);sockets_<<s;auto*t=new QTimer(s);t->setSingleShot(true);auto done=std::make_shared<bool>();auto finish=[this,s,cb=std::move(cb),done](TcpProbe r)mutable{if(*done)return;*done=true;sockets_.removeAll(s);s->abort();s->deleteLater();cb(std::move(r));};connect(s,&QTcpSocket::connected,s,[finish]()mutable{finish({TcpState::Reachable,"Conexão TCP estabelecida e encerrada sem enviar dados."});});connect(s,&QTcpSocket::errorOccurred,s,[s,finish](auto e)mutable{finish({e==QAbstractSocket::ConnectionRefusedError?TcpState::Refused:TcpState::Failed,s->errorString()});});connect(t,&QTimer::timeout,s,[finish]()mutable{finish({TcpState::TimedOut,"Tempo limite da conexão TCP atingido."});});t->start(qBound(100,timeout,10000));s->connectToHost(h,p);}
 void probeFolder(const QString&p,FolderCallback cb)override{QPointer<RealAdapter> self(this);QObject* context=QCoreApplication::instance();QThreadPool::globalInstance()->start([self,context,p,cb=std::move(cb)]()mutable{auto r=folderProbe(p);QMetaObject::invokeMethod(context,[self,cb=std::move(cb),r=std::move(r)]()mutable{if(self)cb(std::move(r));},Qt::QueuedConnection);});}
 void cancelAll()override{for(int id:lookups_)QHostInfo::abortHostLookup(id);lookups_.clear();auto copy=sockets_;sockets_.clear();for(auto*s:copy){s->abort();s->deleteLater();}}
private:QList<int>lookups_;QList<QTcpSocket*>sockets_;};
DiagnosticsService::DiagnosticsService(DiagnosticsAdapter*a,QObject*p):QObject(p),adapter_(a){qRegisterMetaType<DiagnosticsReport>();if(!a){ownedAdapter_=std::make_unique<RealAdapter>(this);adapter_=ownedAdapter_.get();}}
DiagnosticsService::~DiagnosticsService(){cancel();}void DiagnosticsService::cancel(){++generation_;pending_=0;resolvePending_=false;folderPending_=false;checks_.clear();if(adapter_)adapter_->cancelAll();}
quint64 DiagnosticsService::start(const DiagnosticsInput&in){cancel();quint64 id=generation_;input_=in;checks_.clear();
 checks_<<DiagnosticCheck{"discovery",!in.deviceSelected?DiagnosticSeverity::Warning:!in.discovered?DiagnosticSeverity::Error:DiagnosticSeverity::Ok,!in.deviceSelected?"Nenhum computador foi selecionado; descoberta e compatibilidade não foram comprovadas.":!in.discovered?"O computador selecionado não foi encontrado.":"Computador selecionado encontrado.",in.deviceSelected?QStringLiteral("UUID %1").arg(in.deviceUuid.toString(QUuid::WithoutBraces)):QString()};
 checks_<<DiagnosticCheck{"version",in.version.isEmpty()?DiagnosticSeverity::Warning:!in.compatible?DiagnosticSeverity::Error:DiagnosticSeverity::Ok,in.version.isEmpty()?"A versão do computador não foi informada.":!in.compatible?"A versão informada é incompatível.":"A versão informada é compatível.",in.version};
 checks_<<DiagnosticCheck{"dns-ip",DiagnosticSeverity::Warning,"Resolução de endereço pendente.",QStringLiteral("Endpoint %1").arg(in.endpoint)};
 checks_<<DiagnosticCheck{"control-port",in.controlPort?DiagnosticSeverity::Warning:DiagnosticSeverity::Error,in.controlPort?"Teste pendente.":"A porta de controle não foi anunciada; teste não realizado.",{}};
 checks_<<DiagnosticCheck{"transfer-port",(!in.fileTransferCapability||!in.transferPort)?DiagnosticSeverity::Warning:DiagnosticSeverity::Warning,(!in.fileTransferCapability||!in.transferPort)?"Transferência ou porta não anunciada; teste não realizado.":"Teste pendente.",{}};
 checks_<<DiagnosticCheck{"tls-psk",in.hasPairSessionKey&&in.tlsPskCapability?DiagnosticSeverity::Warning:DiagnosticSeverity::Warning,in.hasPairSessionKey&&in.tlsPskCapability?"A proteção TLS-PSK está configurada, mas não foi testada para evitar iniciar uma transferência.":in.tlsPskCapability?"TLS-PSK foi anunciado, mas não há sessão pareada para confirmar a configuração.":"TLS-PSK não foi anunciado pelo computador selecionado.","Nenhum handshake destrutivo foi enviado."};
 checks_<<DiagnosticCheck{"receive-folder",DiagnosticSeverity::Warning,"Teste da pasta pendente.",{}}<<DiagnosticCheck{"folder-permissions",DiagnosticSeverity::Warning,"Teste de permissões pendente.",{}};
 pending_=1;folderPending_=true;QPointer<DiagnosticsService>self(this);adapter_->probeFolder(in.receiveFolder,[self,id](auto r){if(self)self->acceptFolder(id,std::move(r));});
 QTimer::singleShot(qBound(100,in.folderTimeoutMs,10000),this,[self,id](){if(!self||id!=self->generation_||!self->folderPending_)return;self->folderPending_=false;self->checks_[6]={"receive-folder",DiagnosticSeverity::Warning,"O teste da pasta atingiu o tempo limite.",{}};self->checks_[7]={"folder-permissions",DiagnosticSeverity::Warning,"As permissões não foram confirmadas dentro do tempo limite.",{}};self->completeOne(id);});
 const QString host=EndpointPolicy::normalizedHost(in.endpoint);if(EndpointPolicy::isNumeric(host)){if(EndpointPolicy::isUsableUnicast(host)){checks_[2]={"dns-ip",DiagnosticSeverity::Ok,"O endereço IP é unicast utilizável.",host};startTcp(id,host);}else checks_[2]={"dns-ip",DiagnosticSeverity::Error,"O endereço IP não é unicast utilizável ou requer escopo de rede.",host};}
 else if(EndpointPolicy::isUsableUnicast(host)){++pending_;resolvePending_=true;adapter_->resolveHost(host,[self,id](auto r){if(self)self->acceptResolve(id,std::move(r));});QTimer::singleShot(qBound(100,in.networkTimeoutMs,10000),this,[self,id](){if(!self||id!=self->generation_||!self->resolvePending_)return;self->resolvePending_=false;self->checks_[2]={"dns-ip",DiagnosticSeverity::Error,"A resolução do nome atingiu o tempo limite.",{}};self->checks_[3].simple="A porta de controle não foi testada porque a resolução falhou.";self->checks_[4].simple="A porta de transferência não foi testada porque a resolução falhou.";self->completeOne(id);});}
 else checks_[2]={"dns-ip",DiagnosticSeverity::Error,"O endereço está vazio ou tem sintaxe inválida.",host};
 return id;}
void DiagnosticsService::startTcp(quint64 id,const QString&host){QPointer<DiagnosticsService>self(this);if(input_.controlPort){++pending_;adapter_->probeTcp(host,input_.controlPort,input_.networkTimeoutMs,[self,id](auto r){if(self)self->acceptTcp(id,"control-port",std::move(r));});}if(input_.fileTransferCapability&&input_.transferPort){++pending_;adapter_->probeTcp(host,input_.transferPort,input_.networkTimeoutMs,[self,id](auto r){if(self)self->acceptTcp(id,"transfer-port",std::move(r));});}}
void DiagnosticsService::acceptResolve(quint64 id,DiagnosticsAdapter::ResolveProbe p){if(id!=generation_||!resolvePending_)return;resolvePending_=false;QString chosen=EndpointPolicy::firstUsable(p.addresses);if(chosen.isEmpty()){checks_[2]={"dns-ip",DiagnosticSeverity::Error,"O nome não resolveu para um endereço unicast utilizável.",p.technical};checks_[3].simple="A porta de controle não foi testada porque a resolução falhou.";checks_[4].simple="A porta de transferência não foi testada porque a resolução falhou.";}else{checks_[2]={"dns-ip",DiagnosticSeverity::Ok,"O nome foi resolvido para um endereço utilizável.",chosen};startTcp(id,chosen);}completeOne(id);}
void DiagnosticsService::acceptTcp(quint64 id,const QString&cid,DiagnosticsAdapter::TcpProbe p){if(id!=generation_)return;int i=cid=="control-port"?3:4;bool ok=p.state==DiagnosticsAdapter::TcpState::Reachable,timeout=p.state==DiagnosticsAdapter::TcpState::TimedOut;auto fail=(cid=="transfer-port"||timeout)?DiagnosticSeverity::Warning:DiagnosticSeverity::Error;checks_[i]={cid,ok?DiagnosticSeverity::Ok:fail,ok?(cid=="control-port"?"A porta de controle está acessível.":"A porta de transferência está acessível."):timeout?"O teste atingiu o tempo limite.":"Não foi possível acessar a porta.",p.technical};completeOne(id);}
void DiagnosticsService::acceptFolder(quint64 id,DiagnosticsAdapter::FolderProbe p){if(id!=generation_||!folderPending_)return;folderPending_=false;checks_[6]={"receive-folder",p.exists?DiagnosticSeverity::Ok:DiagnosticSeverity::Error,p.exists?"A pasta de recebimento existe.":"A pasta de recebimento não existe.",p.technical};checks_[7]={"folder-permissions",p.writable&&p.permissionProbeSucceeded?DiagnosticSeverity::Ok:DiagnosticSeverity::Error,p.writable&&p.permissionProbeSucceeded?"A pasta permite criar e remover um arquivo temporário seguro.":"Não foi possível confirmar permissão de escrita na pasta.",p.technical};completeOne(id);}
void DiagnosticsService::completeOne(quint64 id){if(id==generation_&&--pending_==0)finalize(id);}void DiagnosticsService::finalize(quint64 id){if(id!=generation_)return;for(auto&c:checks_){c.simple=scrub(c.simple);c.technical=scrub(c.technical);}emit completed(id,{id,aggregate(checks_),checks_});}
