#define OPENSSL_SUPPRESS_DEPRECATED
#include "PairingService.h"
#include <QDateTime>
#include <QHash>
#include <QSet>
#include <openssl/bn.h>
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <openssl/kdf.h>
#include <openssl/rand.h>
#include <openssl/srp.h>
#include <algorithm>
#include <limits>

namespace {
constexpr int MaxAttempts=5,MaxInvites=64,MaxSessions=128; constexpr qint64 MinuteMs=60000;
const QByteArray Domain("InputLeap SRP-6a pairing v2");
void wipe(QByteArray& b){if(!b.isEmpty())OPENSSL_cleanse(b.data(),size_t(b.size()));b.clear();}
QByteArray rnd(qsizetype n){QByteArray b(n,Qt::Uninitialized);if(n<0||RAND_priv_bytes(reinterpret_cast<unsigned char*>(b.data()),int(n))!=1)return {};return b;}
QByteArray lp(const QByteArray& b){QByteArray o;quint32 n=quint32(b.size());for(int s=24;s>=0;s-=8)o.append(char(n>>s));o+=b;return o;}
QByteArray u64(quint64 n){QByteArray o;for(int s=56;s>=0;s-=8)o+=char(n>>s);return o;}
QByteArray i64(qint64 n){return u64(quint64(n));}
QByteArray hash(const QByteArray& b){QByteArray o(32,Qt::Uninitialized);unsigned n=0;if(EVP_Digest(b.constData(),size_t(b.size()),reinterpret_cast<unsigned char*>(o.data()),&n,EVP_sha256(),nullptr)!=1||n!=32)return {};return o;}
QByteArray hmac(const QByteArray& key,const QByteArray& msg){QByteArray o(32,Qt::Uninitialized);unsigned n=0;if(!HMAC(EVP_sha256(),key.constData(),key.size(),reinterpret_cast<const unsigned char*>(msg.constData()),size_t(msg.size()),reinterpret_cast<unsigned char*>(o.data()),&n)||n!=32)return {};return o;}
bool eq(const QByteArray&a,const QByteArray&b){if(a.size()!=b.size())return false;return a.isEmpty()||CRYPTO_memcmp(a.constData(),b.constData(),size_t(a.size()))==0;}
QByteArray ctx(const PairingService::PublicInvite&i){QByteArray o=lp(Domain)+lp(i.inviteId)+lp(i.salt)+lp(i.localUuid.toRfc4122())+lp(i.expectedRemoteUuid.toRfc4122())+lp(i64(i.createdAtMs))+lp(i64(i.expiresAtMs))+lp(u64(i.generation));return o;}
bool same(const PairingService::PublicInvite&a,const PairingService::PublicInvite&b){return a.inviteId==b.inviteId&&a.salt==b.salt&&a.localUuid==b.localUuid&&a.expectedRemoteUuid==b.expectedRemoteUuid&&a.createdAtMs==b.createdAtMs&&a.expiresAtMs==b.expiresAtMs&&a.generation==b.generation;}
bool inviteShape(const PairingService::PublicInvite&i){return i.inviteId.size()==16&&i.salt.size()==16&&!i.localUuid.isNull()&&!i.expectedRemoteUuid.isNull()&&i.localUuid!=i.expectedRemoteUuid&&i.createdAtMs>=0&&i.expiresAtMs>i.createdAtMs&&i.expiresAtMs-i.createdAtMs>=MinuteMs&&i.expiresAtMs-i.createdAtMs<=15*MinuteMs;}
struct Group{BIGNUM*N=nullptr,*g=nullptr,*k=nullptr;int width=0;Group(){auto gn=SRP_get_default_gN("2048");if(!gn)return;N=BN_dup(gn->N);g=BN_dup(gn->g);if(!N||!g)return;width=BN_num_bytes(N);QByteArray z(width,0),gp(width,0);if(width!=256||BN_bn2binpad(N,reinterpret_cast<unsigned char*>(z.data()),width)!=width||BN_bn2binpad(g,reinterpret_cast<unsigned char*>(gp.data()),width)!=width)return;auto kh=hash(z+gp);if(kh.size()==32)k=BN_bin2bn(reinterpret_cast<const unsigned char*>(kh.constData()),kh.size(),nullptr);wipe(kh);wipe(z);wipe(gp);}~Group(){BN_free(N);BN_free(g);BN_free(k);}bool ok()const{return N&&g&&k&&width==256;}};
QByteArray pad(const BIGNUM*n,const Group&g){QByteArray b(g.width,0);if(!n||BN_bn2binpad(n,reinterpret_cast<unsigned char*>(b.data()),g.width)!=g.width)return {};return b;}
BIGNUM* from(const QByteArray&b){return b.isEmpty()?nullptr:BN_bin2bn(reinterpret_cast<const unsigned char*>(b.constData()),b.size(),nullptr);}
BIGNUM* canonicalPublic(const QByteArray&b,const Group&g){if(b.size()!=g.width)return nullptr;BIGNUM*n=from(b);if(!n||BN_is_zero(n)||BN_is_negative(n)||BN_cmp(n,g.N)>=0){BN_clear_free(n);return nullptr;}return n;}
bool publicOk(const BIGNUM*n,const Group&g){BN_CTX*c=BN_CTX_new();BIGNUM*r=BN_new();bool ok=c&&r&&BN_mod(r,n,g.N,c)&&!BN_is_zero(r);BN_clear_free(r);BN_CTX_free(c);return ok;}
BIGNUM* privateBn(const PairingService::RandomBytes&r,const Group&g){int bytes=g.width;for(int tries=0;tries<128;++tries){QByteArray b=r(bytes);if(b.size()!=bytes)return nullptr;BIGNUM*x=from(b);wipe(b);if(x&& !BN_is_zero(x)&&BN_cmp(x,g.N)<0)return x;BN_clear_free(x);}return nullptr;}
QByteArray displayCode(const PairingService::RandomBytes&r){constexpr quint64 Range=quint64(std::numeric_limits<quint32>::max())+1;constexpr quint64 Limit=(Range/1'000'000)*1'000'000;for(int tries=0;tries<128;++tries){QByteArray b=r(4);if(b.size()!=4)return{};quint32 n=0;for(unsigned char c:b)n=(n<<8)|c;wipe(b);if(quint64(n)<Limit)return QByteArray::number(n%1'000'000).rightJustified(6,'0');}return{};}
BIGNUM* calcX(const QByteArray&code,const PairingService::PublicInvite&i){if(code.size()!=6||!inviteShape(i))return nullptr;QByteArray ident=ctx(i);QByteArray inner=hash(lp(ident)+QByteArray(":")+lp(code));if(inner.size()!=32){wipe(ident);wipe(inner);return nullptr;}QByteArray xh=hash(lp(i.salt)+lp(inner));BIGNUM*x=xh.size()==32?from(xh):nullptr;wipe(inner);wipe(xh);wipe(ident);return x;}
QByteArray proof1(const Group&g,const PairingService::PublicInvite&i,const BIGNUM*A,const BIGNUM*B,const QByteArray&K){auto pn=pad(g.N,g),pg=pad(g.g,g),pa=pad(A,g),pb=pad(B,g);auto hn=hash(pn),hg=hash(pg),hc=hash(ctx(i));if(pn.size()!=g.width||pg.size()!=g.width||pa.size()!=g.width||pb.size()!=g.width||hn.size()!=32||hg.size()!=32||hc.size()!=32||K.size()!=32){wipe(pn);wipe(pg);wipe(pa);wipe(pb);wipe(hn);wipe(hg);wipe(hc);return{};}for(int z=0;z<32;++z)hn[z]^=hg[z];QByteArray m=lp(QByteArray("M1"))+lp(Domain)+lp(hn)+lp(hc)+lp(i.salt)+lp(pa)+lp(pb)+lp(K);wipe(pn);wipe(pg);wipe(pa);wipe(pb);wipe(hn);wipe(hg);wipe(hc);return hash(m);}
QByteArray proof2(const Group&g,const PairingService::PublicInvite&i,const BIGNUM*A,const QByteArray&M1,const QByteArray&K){auto pa=pad(A,g),hc=hash(ctx(i));if(pa.size()!=g.width||hc.size()!=32||M1.size()!=32||K.size()!=32){wipe(pa);wipe(hc);return{};}QByteArray result=hash(lp(QByteArray("M2"))+lp(Domain)+lp(pa)+lp(M1)+lp(K)+lp(hc));wipe(pa);wipe(hc);return result;}
QByteArray derive(const QByteArray&K,const QByteArray&transcript,const QByteArray&salt){if(K.size()!=32||transcript.isEmpty()||salt.size()!=16)return{};QByteArray key(32,Qt::Uninitialized);EVP_PKEY_CTX*c=EVP_PKEY_CTX_new_id(EVP_PKEY_HKDF,nullptr);size_t n=32;bool ok=c&&EVP_PKEY_derive_init(c)>0&&EVP_PKEY_CTX_set_hkdf_md(c,EVP_sha256())>0&&EVP_PKEY_CTX_set1_hkdf_salt(c,reinterpret_cast<const unsigned char*>(salt.constData()),salt.size())>0&&EVP_PKEY_CTX_set1_hkdf_key(c,reinterpret_cast<const unsigned char*>(K.constData()),K.size())>0&&EVP_PKEY_CTX_add1_hkdf_info(c,reinterpret_cast<const unsigned char*>(transcript.constData()),transcript.size())>0&&EVP_PKEY_derive(c,reinterpret_cast<unsigned char*>(key.data()),&n)>0;EVP_PKEY_CTX_free(c);if(!ok||n!=32)wipe(key);return key;}
QByteArray transcript(const PairingService::PublicInvite&i,const QByteArray&sid,const BIGNUM*A,const BIGNUM*B,const QByteArray&M1,const QByteArray&M2,const Group&g){auto pa=pad(A,g),pb=pad(B,g);if(sid.size()!=16||pa.size()!=g.width||pb.size()!=g.width||M1.size()!=32||M2.size()!=32){wipe(pa);wipe(pb);return{};}QByteArray result=lp(Domain)+lp(ctx(i))+lp(sid)+lp(pa)+lp(pb)+lp(M1)+lp(M2);wipe(pa);wipe(pb);return result;}
}

struct PairingService::Impl{
 struct Invite{PublicInvite p;BIGNUM*v=nullptr;int attempts=0;bool revoked=false;~Invite(){BN_clear_free(v);}};
 struct Session{enum Role{Client,Server}role;PublicInvite p;QByteArray id,code,K,M1,M2,key,trans;BIGNUM*secret=nullptr,*A=nullptr,*B=nullptr;~Session(){wipe(code);wipe(K);wipe(key);wipe(trans);BN_clear_free(secret);BN_clear_free(A);BN_clear_free(B);}};
 Clock clock;RandomBytes random;Group group;Status status=Status::Ok;QHash<QByteArray,std::shared_ptr<Invite>> invites;QHash<QByteArray,std::shared_ptr<Session>> sessions;QSet<QByteArray> consumedSessions;QHash<QUuid,quint64> generations;QHash<QUuid,QByteArray> keys;
 Impl(Clock c,RandomBytes r):clock(c?std::move(c):Clock([]{return QDateTime::currentMSecsSinceEpoch();})),random(r?std::move(r):RandomBytes(rnd)){}
 ~Impl(){for(auto&k:keys)wipe(k);}
 void set(Status s){status=s;}
 bool live(const PublicInvite&i){qint64 n=clock();if(n<i.createdAtMs){set(Status::InvalidClock);return false;}if(n>=i.expiresAtMs){set(Status::Expired);return false;}return true;}
 void purge(){qint64 n=clock();for(auto it=sessions.begin();it!=sessions.end();)it=(n>=it.value()->p.expiresAtMs)?sessions.erase(it):++it;for(auto it=invites.begin();it!=invites.end();)it=(n>=it.value()->p.expiresAtMs)?invites.erase(it):++it;}
};
QJsonObject PairingService::PublicInvite::toJson()const{return{{"inviteId",QString::fromLatin1(inviteId.toBase64(QByteArray::Base64UrlEncoding|QByteArray::OmitTrailingEquals))},{"salt",QString::fromLatin1(salt.toBase64(QByteArray::Base64UrlEncoding|QByteArray::OmitTrailingEquals))},{"localUuid",localUuid.toString(QUuid::WithoutBraces)},{"expectedRemoteUuid",expectedRemoteUuid.toString(QUuid::WithoutBraces)},{"createdAtMs",QString::number(createdAtMs)},{"expiresAtMs",QString::number(expiresAtMs)},{"generation",QString::number(generation)}};}
PairingService::PairingService(Clock c,RandomBytes r):d(std::make_unique<Impl>(std::move(c),std::move(r))){} PairingService::~PairingService()=default;
std::optional<PairingService::CreatedInvite> PairingService::createInvite(const QUuid&local,const QUuid&remote,int mins){d->purge();if(!d->group.ok()){d->set(Status::CryptoError);return{};}if(local.isNull()||remote.isNull()||local==remote){d->set(Status::InvalidIdentity);return{};}if(mins<1||mins>15){d->set(Status::Malformed);return{};}for(auto&s:d->invites)if(s->p.expectedRemoteUuid==remote&&!s->revoked){d->set(Status::ResourceLimit);return{};}if(d->invites.size()>=MaxInvites){d->set(Status::ResourceLimit);return{};}qint64 now=d->clock();if(now<0||now>std::numeric_limits<qint64>::max()-mins*MinuteMs){d->set(Status::InvalidClock);return{};}PublicInvite p{d->random(16),d->random(16),local,remote,now,now+mins*MinuteMs,d->generations.value(remote)};QByteArray code=displayCode(d->random);if(p.inviteId.size()!=16||p.salt.size()<16||code.size()!=6||d->invites.contains(p.inviteId)){wipe(code);d->set(Status::CryptoError);return{};}BIGNUM*x=calcX(code,p);BN_CTX*c=BN_CTX_new();BIGNUM*v=BN_new();bool ok=x&&c&&v&&BN_mod_exp(v,d->group.g,x,d->group.N,c);BN_clear_free(x);BN_CTX_free(c);if(!ok){BN_clear_free(v);wipe(code);d->set(Status::CryptoError);return{};}auto state=std::make_shared<Impl::Invite>();state->p=p;state->v=v;d->invites.insert(p.inviteId,state);d->set(Status::Ok);return CreatedInvite{p,code};}
std::optional<PairingService::ClientHello> PairingService::beginPairing(const PublicInvite&p,const QByteArray&code,const QUuid&remote,const QUuid&local){d->purge();if(!inviteShape(p)){d->set(Status::InvalidInvite);return{};}if(remote.isNull()||local.isNull()||remote==local){d->set(Status::InvalidIdentity);return{};}if(remote!=p.expectedRemoteUuid||local!=p.localUuid){d->set(Status::IdentityMismatch);return{};}if(code.size()!=6||std::any_of(code.begin(),code.end(),[](char c){return c<'0'||c>'9';})){d->set(Status::Malformed);return{};}if(!d->live(p))return{};if(d->sessions.size()>=MaxSessions){d->set(Status::ResourceLimit);return{};}BIGNUM*a=privateBn(d->random,d->group);BN_CTX*c=BN_CTX_new();BIGNUM*A=BN_new();QByteArray sid=d->random(16);bool ok=a&&c&&A&&sid.size()==16&&BN_mod_exp(A,d->group.g,a,d->group.N,c)&&publicOk(A,d->group)&&!d->sessions.contains(sid);BN_CTX_free(c);if(!ok){BN_clear_free(a);BN_clear_free(A);d->set(Status::CryptoError);return{};}auto s=std::make_shared<Impl::Session>();s->role=Impl::Session::Client;s->p=p;s->id=sid;s->code=code;s->secret=a;s->A=A;d->sessions[sid]=s;d->set(Status::Ok);return ClientHello{sid,pad(A,d->group),p.inviteId};}
std::optional<PairingService::ServerChallenge> PairingService::respondToClient(const PublicInvite&p,const ClientHello&h){d->purge();auto ii=d->invites.find(p.inviteId);if(ii==d->invites.end()){d->set(Status::UnknownInvite);return{};}auto in=*ii;if(!same(p,in->p)||h.inviteId!=p.inviteId){d->set(Status::InvalidInvite);return{};}if(in->revoked||p.generation!=d->generations.value(p.expectedRemoteUuid)){d->set(Status::Revoked);return{};}if(in->attempts>=MaxAttempts){d->set(Status::AttemptLimitReached);return{};}if(!d->live(p))return{};for(auto it=d->sessions.begin();it!=d->sessions.end();)it=(it.value()->role==Impl::Session::Server&&it.value()->p.inviteId==p.inviteId)?d->sessions.erase(it):++it;if(d->sessions.size()>=MaxSessions){d->set(Status::ResourceLimit);return{};}if(h.sessionId.size()!=16||d->sessions.contains(h.sessionId)){d->set(Status::UnknownSession);return{};}BIGNUM*A=canonicalPublic(h.A,d->group);if(!A){BN_clear_free(A);d->set(Status::InvalidPublicValue);return{};}BIGNUM*b=privateBn(d->random,d->group),*gb=BN_new(),*kv=BN_new(),*B=BN_new();BN_CTX*c=BN_CTX_new();bool ok=b&&gb&&kv&&B&&c&&BN_mod_exp(gb,d->group.g,b,d->group.N,c)&&BN_mod_mul(kv,d->group.k,in->v,d->group.N,c)&&BN_mod_add(B,kv,gb,d->group.N,c)&&publicOk(B,d->group);BN_clear_free(gb);BN_clear_free(kv);BN_CTX_free(c);if(!ok){BN_clear_free(A);BN_clear_free(b);BN_clear_free(B);d->set(Status::CryptoError);return{};}auto s=std::make_shared<Impl::Session>();s->role=Impl::Session::Server;s->p=p;s->id=h.sessionId;s->secret=b;s->A=A;s->B=B;d->sessions[h.sessionId]=s;d->set(Status::Ok);return ServerChallenge{h.sessionId,pad(B,d->group),p.inviteId};}
std::optional<PairingService::ClientProof> PairingService::answerChallenge(const ServerChallenge&ch){auto it=d->sessions.find(ch.sessionId);if(it==d->sessions.end()||(*it)->role!=Impl::Session::Client||ch.inviteId!=(*it)->p.inviteId){d->set(Status::UnknownSession);return{};}auto s=*it;if(!d->live(s->p)){d->sessions.erase(it);return{};}BIGNUM*B=canonicalPublic(ch.B,d->group);if(!B){BN_clear_free(B);d->set(Status::InvalidPublicValue);return{};}QByteArray pa=pad(s->A,d->group),pb=pad(B,d->group);QByteArray uh=(pa.size()==d->group.width&&pb.size()==d->group.width)?hash(pa+pb):QByteArray();wipe(pa);wipe(pb);BIGNUM*u=from(uh),*x=calcX(s->code,s->p),*gx=BN_new(),*kgx=BN_new(),*base=BN_new(),*ux=BN_new(),*exp=BN_new(),*S=BN_new();BN_CTX*c=BN_CTX_new();bool ok=uh.size()==32&&u&&!BN_is_zero(u)&&x&&gx&&kgx&&base&&ux&&exp&&S&&c&&BN_mod_exp(gx,d->group.g,x,d->group.N,c)&&BN_mod_mul(kgx,d->group.k,gx,d->group.N,c)&&BN_mod_sub(base,B,kgx,d->group.N,c)&&!BN_is_zero(base)&&BN_mul(ux,u,x,c)&&BN_add(exp,s->secret,ux)&&BN_mod_exp(S,base,exp,d->group.N,c)&&!BN_is_zero(S);wipe(uh);BN_clear_free(x);BN_clear_free(gx);BN_clear_free(kgx);BN_clear_free(base);BN_clear_free(ux);BN_clear_free(exp);BN_CTX_free(c);if(!ok){BN_clear_free(u);BN_clear_free(S);BN_clear_free(B);d->sessions.erase(it);d->set(Status::CryptoError);return{};}s->B=B;QByteArray sp=pad(S,d->group);s->K=sp.size()==d->group.width?hash(sp):QByteArray();wipe(sp);s->M1=proof1(d->group,s->p,s->A,s->B,s->K);BN_clear_free(S);BN_clear_free(u);wipe(s->code);if(s->K.size()!=32||s->M1.size()!=32){d->sessions.erase(it);d->set(Status::CryptoError);return{};}d->set(Status::Ok);return ClientProof{s->id,s->M1};}
std::optional<PairingService::ServerProof> PairingService::verifyClientProof(const ClientProof&p){auto it=d->sessions.find(p.sessionId);if(it==d->sessions.end()||(*it)->role!=Impl::Session::Server){d->set(Status::UnknownSession);return{};}auto s=*it;auto ii=d->invites.find(s->p.inviteId);if(ii==d->invites.end()){d->set(Status::UnknownInvite);return{};}auto in=*ii;if(!d->live(s->p)){d->sessions.erase(it);return{};}if(in->attempts>=MaxAttempts){d->set(Status::AttemptLimitReached);return{};}if(p.M1.size()!=32){++in->attempts;d->sessions.erase(it);d->set(in->attempts>=MaxAttempts?Status::AttemptLimitReached:Status::InvalidProof);return{};}QByteArray pa=pad(s->A,d->group),pb=pad(s->B,d->group);QByteArray uh=(pa.size()==d->group.width&&pb.size()==d->group.width)?hash(pa+pb):QByteArray();wipe(pa);wipe(pb);BIGNUM*u=from(uh),*vu=BN_new(),*av=BN_new(),*S=BN_new();BN_CTX*c=BN_CTX_new();bool ok=uh.size()==32&&u&&!BN_is_zero(u)&&vu&&av&&S&&c&&BN_mod_exp(vu,in->v,u,d->group.N,c)&&BN_mod_mul(av,s->A,vu,d->group.N,c)&&BN_mod_exp(S,av,s->secret,d->group.N,c)&&!BN_is_zero(S);wipe(uh);BN_clear_free(u);BN_clear_free(vu);BN_clear_free(av);BN_CTX_free(c);if(!ok){BN_clear_free(S);d->sessions.erase(it);d->set(Status::CryptoError);return{};}QByteArray sp=pad(S,d->group);s->K=sp.size()==d->group.width?hash(sp):QByteArray();wipe(sp);BN_clear_free(S);if(s->K.size()!=32){d->sessions.erase(it);d->set(Status::CryptoError);return{};}QByteArray expected=proof1(d->group,s->p,s->A,s->B,s->K);if(expected.size()!=32){d->sessions.erase(it);d->set(Status::CryptoError);return{};}if(!eq(expected,p.M1)){++in->attempts;d->sessions.erase(it);d->set(in->attempts>=MaxAttempts?Status::AttemptLimitReached:Status::InvalidProof);return{};}s->M1=expected;s->M2=proof2(d->group,s->p,s->A,s->M1,s->K);s->trans=transcript(s->p,s->id,s->A,s->B,s->M1,s->M2,d->group);s->key=derive(s->K,s->trans,s->p.salt);if(s->key.size()!=32){d->sessions.erase(it);d->set(Status::CryptoError);return{};}d->set(Status::Ok);return ServerProof{s->id,s->M2};}
std::optional<PairingService::FinalAck> PairingService::verifyServerProof(const ServerProof&p){auto it=d->sessions.find(p.sessionId);if(it==d->sessions.end()||(*it)->role!=Impl::Session::Client){d->set(Status::UnknownSession);return{};}auto s=*it;if(!d->live(s->p)){d->sessions.erase(it);return{};}if(p.M2.size()!=32){d->sessions.erase(it);d->set(Status::InvalidProof);return{};}QByteArray expected=proof2(d->group,s->p,s->A,s->M1,s->K);if(expected.size()!=32){d->sessions.erase(it);d->set(Status::CryptoError);return{};}if(!eq(expected,p.M2)){d->set(Status::InvalidProof);return{};}s->M2=expected;s->trans=transcript(s->p,s->id,s->A,s->B,s->M1,s->M2,d->group);s->key=derive(s->K,s->trans,s->p.salt);if(s->key.size()!=32){d->sessions.erase(it);d->set(Status::CryptoError);return{};}QByteArray m3=hmac(s->key,lp(QByteArray("M3"))+lp(s->trans)+lp(s->M2));if(m3.size()!=32){d->sessions.erase(it);d->set(Status::CryptoError);return{};}auto old=d->keys.find(s->p.localUuid);if(old!=d->keys.end())wipe(*old);d->keys[s->p.localUuid]=s->key;d->sessions.erase(it);d->set(Status::Accepted);return FinalAck{s->id,m3};}
PairingService::Status PairingService::finalize(const FinalAck&a){auto it=d->sessions.find(a.sessionId);if(it==d->sessions.end()){d->set(d->consumedSessions.contains(a.sessionId)?Status::AlreadyUsed:Status::UnknownSession);return d->status;}auto s=*it;if(!d->live(s->p)){d->sessions.erase(it);return d->status;}if(s->role!=Impl::Session::Server||s->key.size()!=32){d->set(Status::UnknownSession);return d->status;}if(a.M3.size()!=32){d->set(Status::InvalidProof);return d->status;}QByteArray expected=hmac(s->key,lp(QByteArray("M3"))+lp(s->trans)+lp(s->M2));if(expected.size()!=32){d->sessions.erase(it);d->set(Status::CryptoError);return d->status;}if(!eq(expected,a.M3)){d->set(Status::InvalidProof);return d->status;}auto old=d->keys.find(s->p.expectedRemoteUuid);if(old!=d->keys.end())wipe(*old);d->keys[s->p.expectedRemoteUuid]=s->key;d->invites.remove(s->p.inviteId);d->sessions.remove(a.sessionId);if(d->consumedSessions.size()>=64)d->consumedSessions.erase(d->consumedSessions.begin());d->consumedSessions.insert(a.sessionId);d->set(Status::Accepted);return d->status;}
void PairingService::revoke(const QUuid&r){if(r.isNull())return;for(auto it=d->invites.begin();it!=d->invites.end();)it=(it.value()->p.expectedRemoteUuid==r)?d->invites.erase(it):++it;for(auto it=d->sessions.begin();it!=d->sessions.end();)it=(it.value()->p.expectedRemoteUuid==r||it.value()->p.localUuid==r)?d->sessions.erase(it):++it;auto k=d->keys.find(r);if(k!=d->keys.end()){wipe(*k);d->keys.erase(k);}}
quint64 PairingService::rotate(const QUuid&r){if(r.isNull())return 0;revoke(r);auto&g=d->generations[r];if(g<std::numeric_limits<quint64>::max())++g;return g;}
std::optional<QByteArray> PairingService::pairKey(const QUuid&r)const{auto it=d->keys.constFind(r);return it==d->keys.cend()?std::nullopt:std::optional<QByteArray>(*it);} PairingService::Status PairingService::lastStatus()const{return d->status;}
