#include "PairingProtocolCodec.h"
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <cmath>
#include <algorithm>
#include <QSet>

namespace {
const QByteArray MetadataDomain("inputleap/pairing/device-metadata/v1");
QString b64(const QByteArray& b){return QString::fromLatin1(b.toBase64(QByteArray::Base64UrlEncoding|QByteArray::OmitTrailingEquals));}
bool unb64(const QJsonValue& v,QByteArray* out,int exact=-1){if(!v.isString())return false; auto s=v.toString().toLatin1(); *out=QByteArray::fromBase64(s,QByteArray::Base64UrlEncoding|QByteArray::AbortOnBase64DecodingErrors); return (exact<0||out->size()==exact)&&b64(*out).toLatin1()==s;}
QString name(PairingProtocolCodec::Type t){switch(t){case PairingProtocolCodec::Type::Invite:return "invite";case PairingProtocolCodec::Type::Hello:return "hello";case PairingProtocolCodec::Type::Challenge:return "challenge";case PairingProtocolCodec::Type::ClientProof:return "m1";case PairingProtocolCodec::Type::ServerProof:return "m2";case PairingProtocolCodec::Type::FinalAck:return "m3";case PairingProtocolCodec::Type::Success:return "success";case PairingProtocolCodec::Type::Confirmed:return "confirmed";case PairingProtocolCodec::Type::DeviceMetadata:return "deviceMetadata";case PairingProtocolCodec::Type::Error:return "error";}return {};}
bool type(const QString&s,PairingProtocolCodec::Type*out){for(auto t:{PairingProtocolCodec::Type::Invite,PairingProtocolCodec::Type::Hello,PairingProtocolCodec::Type::Challenge,PairingProtocolCodec::Type::ClientProof,PairingProtocolCodec::Type::ServerProof,PairingProtocolCodec::Type::FinalAck,PairingProtocolCodec::Type::Success,PairingProtocolCodec::Type::Confirmed,PairingProtocolCodec::Type::DeviceMetadata,PairingProtocolCodec::Type::Error})if(name(t)==s){*out=t;return true;}return false;}
bool i64(const QJsonValue&v,qint64*out){if(!v.isString())return false;bool ok=false;*out=v.toString().toLongLong(&ok);return ok&&QString::number(*out)==v.toString();}
bool u64(const QJsonValue&v,quint64*out){if(!v.isString())return false;bool ok=false;*out=v.toString().toULongLong(&ok);return ok&&QString::number(*out)==v.toString();}
void append32(QByteArray&o,qint32 n){quint32 u=quint32(n);for(int s=24;s>=0;s-=8)o.append(char(u>>s));}
void appendBytes(QByteArray&o,const QByteArray&b){append32(o,b.size());o+=b;}
bool validOrientation(Qt::ScreenOrientation o){return o==Qt::PrimaryOrientation||o==Qt::PortraitOrientation||o==Qt::LandscapeOrientation||o==Qt::InvertedPortraitOrientation||o==Qt::InvertedLandscapeOrientation;}
bool validMonitor(const ScreenLayout::Monitor&m){const auto&r=m.geometry;const qint64 right=qint64(r.x())+r.width(),bottom=qint64(r.y())+r.height();return !m.id.isEmpty()&&m.id.toUtf8().size()<=ScreenLayout::MaxMonitorIdBytes&&r.x()>=0&&r.y()>=0&&r.width()>0&&r.height()>0&&right<=ScreenLayout::MaxCoordinate&&bottom<=ScreenLayout::MaxCoordinate&&r.width()<=ScreenLayout::MaxExtent&&r.height()<=ScreenLayout::MaxExtent&&std::isfinite(double(m.devicePixelRatio))&&m.devicePixelRatio>=0.25&&m.devicePixelRatio<=16.0&&validOrientation(m.orientation);}
QByteArray canonical(const PairingProtocolCodec::Message&m){
    if(m.type!=PairingProtocolCodec::Type::DeviceMetadata||m.sessionId.size()!=16||m.inviteId.size()!=16||m.senderUuid.isNull()||m.receiverUuid.isNull()||m.senderUuid==m.receiverUuid||m.monitors.empty()||m.monitors.size()>ScreenLayout::MaxMonitorsPerDevice)return{};
    QByteArray o;appendBytes(o,MetadataDomain);appendBytes(o,m.inviteId);appendBytes(o,m.sessionId);appendBytes(o,m.senderUuid.toRfc4122());appendBytes(o,m.receiverUuid.toRfc4122());append32(o,qint32(m.monitors.size()));
    QSet<QString> ids;std::vector<QRect> rectangles;
    for(const auto&monitor:m.monitors){if(!validMonitor(monitor)||ids.contains(monitor.id)||std::any_of(rectangles.begin(),rectangles.end(),[&](const QRect&r){return r.intersects(monitor.geometry);}))return{};ids.insert(monitor.id);rectangles.push_back(monitor.geometry);appendBytes(o,monitor.id.toUtf8());append32(o,monitor.geometry.x());append32(o,monitor.geometry.y());append32(o,monitor.geometry.width());append32(o,monitor.geometry.height());quint64 bits=0;const double d=double(monitor.devicePixelRatio);static_assert(sizeof(bits)==sizeof(d));memcpy(&bits,&d,sizeof(bits));for(int s=56;s>=0;s-=8)o.append(char(bits>>s));append32(o,int(monitor.orientation));o.append(monitor.stableIdentity?'\1':'\0');}return o;
}
QByteArray mac(const QByteArray&key,const QByteArray&data){if(key.size()!=32||data.isEmpty())return{};QByteArray out(32,Qt::Uninitialized);unsigned n=0;if(!HMAC(EVP_sha256(),key.constData(),key.size(),reinterpret_cast<const unsigned char*>(data.constData()),size_t(data.size()),reinterpret_cast<unsigned char*>(out.data()),&n)||n!=32)return{};return out;}
}
PairingProtocolCodec::Message PairingProtocolCodec::invite(const PairingService::PublicInvite&i){Message m;m.type=Type::Invite;m.invite=i;return m;}
PairingProtocolCodec::Message PairingProtocolCodec::success(const QByteArray&s){Message m;m.type=Type::Success;m.sessionId=s;return m;}
PairingProtocolCodec::Message PairingProtocolCodec::confirmed(const QByteArray&s){Message m;m.type=Type::Confirmed;m.sessionId=s;return m;}
std::optional<PairingProtocolCodec::Message> PairingProtocolCodec::deviceMetadata(const QByteArray&key,const QByteArray&sid,const QByteArray&iid,const QUuid&sender,const QUuid&receiver,const std::vector<ScreenLayout::Monitor>&monitors){Message m;m.type=Type::DeviceMetadata;m.sessionId=sid;m.inviteId=iid;m.senderUuid=sender;m.receiverUuid=receiver;m.monitors=monitors;auto bytes=canonical(m);m.authenticationTag=mac(key,bytes);if(bytes.isEmpty()||m.authenticationTag.size()!=32)return{};return m;}
bool PairingProtocolCodec::authenticateDeviceMetadata(const Message&m,const QByteArray&key,const QByteArray&sid,const QByteArray&iid,const QUuid&sender,const QUuid&receiver){if(m.type!=Type::DeviceMetadata||m.sessionId!=sid||m.inviteId!=iid||m.senderUuid!=sender||m.receiverUuid!=receiver||m.authenticationTag.size()!=32)return false;auto expected=mac(key,canonical(m));return expected.size()==32&&CRYPTO_memcmp(expected.constData(),m.authenticationTag.constData(),32)==0;}
PairingProtocolCodec::Message PairingProtocolCodec::error(const QString&e){Message m;m.type=Type::Error;m.error=e.left(256);return m;}
QByteArray PairingProtocolCodec::encode(const Message&m){QJsonObject f;if(m.type==Type::Invite)f=m.invite.toJson();else if(m.type==Type::DeviceMetadata){f={{"sessionId",b64(m.sessionId)},{"inviteId",b64(m.inviteId)},{"senderUuid",m.senderUuid.toString(QUuid::WithoutBraces)},{"receiverUuid",m.receiverUuid.toString(QUuid::WithoutBraces)},{"tag",b64(m.authenticationTag)}};QJsonArray a;for(const auto&x:m.monitors)a.append(QJsonObject{{"id",x.id},{"x",QString::number(x.geometry.x())},{"y",QString::number(x.geometry.y())},{"width",QString::number(x.geometry.width())},{"height",QString::number(x.geometry.height())},{"dpr",QString::number(double(x.devicePixelRatio),'g',17)},{"orientation",int(x.orientation)},{"stable",x.stableIdentity}});f["monitors"]=a;}else {if(!m.sessionId.isEmpty())f["sessionId"]=b64(m.sessionId);if(!m.inviteId.isEmpty())f["inviteId"]=b64(m.inviteId);if(!m.value.isEmpty())f["value"]=b64(m.value);if(m.type==Type::Error)f["message"]=m.error.left(256);}QJsonObject root{{"fields",f},{"type",name(m.type)},{"version",int(Version)}};QByteArray p=QJsonDocument(root).toJson(QJsonDocument::Compact);if(p.isEmpty()||p.size()>int(MaxPayload))return{};QByteArray out;quint32 n=p.size();for(int s=24;s>=0;s-=8)out.append(char(n>>s));return out+p;}
bool PairingProtocolCodec::decodeFrame(const QByteArray&f,Message*m,QString*e){if(f.size()<4){if(e)*e="Cabeçalho incompleto";return false;}quint32 n=0;for(int i=0;i<4;i++)n=(n<<8)|quint8(f[i]);if(n==0||n>MaxPayload||f.size()!=int(n)+4){if(e)*e="Tamanho de quadro inválido";return false;}return decodePayload(f.mid(4),m,e);}
bool PairingProtocolCodec::decodePayload(const QByteArray&p,Message*m,QString*e){if(!m||p.isEmpty()||p.size()>int(MaxPayload)){if(e)*e="Mensagem inválida";return false;}QJsonParseError pe;auto d=QJsonDocument::fromJson(p,&pe);if(pe.error!=QJsonParseError::NoError||!d.isObject()){if(e)*e="JSON inválido";return false;}auto r=d.object();if(r.size()!=3||r.value("version").toInt(-1)!=int(Version)||!r.value("type").isString()||!r.value("fields").isObject()){if(e)*e="Versão ou formato desconhecido";return false;}Message x;if(!type(r.value("type").toString(),&x.type)){if(e)*e="Tipo desconhecido";return false;}auto f=r.value("fields").toObject();if(x.type==Type::Invite){if(f.size()!=7||!unb64(f.value("inviteId"),&x.invite.inviteId,16)||!unb64(f.value("salt"),&x.invite.salt,16)){if(e)*e="Convite inválido";return false;}x.invite.localUuid=QUuid(f.value("localUuid").toString());x.invite.expectedRemoteUuid=QUuid(f.value("expectedRemoteUuid").toString());if(x.invite.localUuid.isNull()||x.invite.expectedRemoteUuid.isNull()||!i64(f.value("createdAtMs"),&x.invite.createdAtMs)||!i64(f.value("expiresAtMs"),&x.invite.expiresAtMs)||!u64(f.value("generation"),&x.invite.generation)){if(e)*e="Convite inválido";return false;}}
else if(x.type==Type::DeviceMetadata){if(f.size()!=6||!unb64(f.value("sessionId"),&x.sessionId,16)||!unb64(f.value("inviteId"),&x.inviteId,16)||!unb64(f.value("tag"),&x.authenticationTag,32)||!f.value("monitors").isArray())return false;x.senderUuid=QUuid(f.value("senderUuid").toString());x.receiverUuid=QUuid(f.value("receiverUuid").toString());auto a=f.value("monitors").toArray();if(x.senderUuid.isNull()||x.receiverUuid.isNull()||a.isEmpty()||a.size()>ScreenLayout::MaxMonitorsPerDevice)return false;for(const auto&v:a){if(!v.isObject())return false;auto z=v.toObject();if(z.size()!=8||!z.value("id").isString()||!z.value("dpr").isString()||!z.value("stable").isBool())return false;qint64 px=0,py=0,pw=0,ph=0;if(!i64(z.value("x"),&px)||!i64(z.value("y"),&py)||!i64(z.value("width"),&pw)||!i64(z.value("height"),&ph)||px<INT_MIN||px>INT_MAX||py<INT_MIN||py>INT_MAX||pw<INT_MIN||pw>INT_MAX||ph<INT_MIN||ph>INT_MAX)return false;bool ok=false;double dpr=z.value("dpr").toString().toDouble(&ok);auto orientation=Qt::ScreenOrientation(z.value("orientation").toInt(-1));ScreenLayout::Monitor monitor{z.value("id").toString(),QRect(int(px),int(py),int(pw),int(ph)),dpr,orientation,z.value("stable").toBool()};if(!ok||QString::number(dpr,'g',17)!=z.value("dpr").toString()||!validMonitor(monitor))return false;x.monitors.push_back(std::move(monitor));}}
else {if(x.type==Type::Error){if(f.size()!=1||!f.value("message").isString()||f.value("message").toString().isEmpty()||f.value("message").toString().size()>256)return false;x.error=f.value("message").toString();}else if(x.type==Type::Success||x.type==Type::Confirmed){if(f.size()!=1||!unb64(f.value("sessionId"),&x.sessionId,16))return false;}else {const int valueSize=(x.type==Type::Hello||x.type==Type::Challenge)?256:32;if(f.size()!=3||!unb64(f.value("sessionId"),&x.sessionId,16)||!unb64(f.value("inviteId"),&x.inviteId,16)||!unb64(f.value("value"),&x.value,valueSize))return false;}}*m=x;return true;}
