/* InputLeap -- mouse and keyboard sharing utility */
#include "ScreenLayoutEditorWidget.h"
#include <QKeyEvent>
#include <QMouseEvent>
#include <QApplication>
#include <QPainter>
#include <algorithm>
#include <limits>

ScreenLayoutEditorViewModel::ScreenLayoutEditorViewModel(ScreenLayout layout,QUuid localUuid):layout_(std::move(layout)),localUuid_(std::move(localUuid)){}
const ScreenLayout::Device* ScreenLayoutEditorViewModel::device(const QUuid& uuid) const { for(const auto& d:layout_.devices()) if(d.uuid==uuid)return &d; return nullptr; }
bool ScreenLayoutEditorViewModel::moveAdjacent(const QUuid& moving,const QUuid& anchor,Direction direction)
{
    auto devices=layout_.devices(); auto m=std::find_if(devices.begin(),devices.end(),[&](const auto& d){return d.uuid==moving;});
    auto a=std::find_if(devices.begin(),devices.end(),[&](const auto& d){return d.uuid==anchor;});
    if(m==devices.end()||a==devices.end()||m==a)return false;
    QRect target(QPoint(),m->geometry.size()); switch(direction){case Direction::Left:target.moveTopRight({a->geometry.left()-1,a->geometry.top()});break;case Direction::Right:target.moveTopLeft({a->geometry.right()+1,a->geometry.top()});break;case Direction::Above:target.moveBottomLeft({a->geometry.left(),a->geometry.top()-1});break;case Direction::Below:target.moveTopLeft({a->geometry.left(),a->geometry.bottom()+1});break;}
    for(const auto& d:devices)if(d.uuid!=moving&&d.geometry.intersects(target))return false;
    m->geometry=target; ScreenLayout candidate(std::move(devices)); if(!candidate.validate().isValid())return false; layout_=std::move(candidate); return true;
}
std::optional<QStringList> ScreenLayoutEditorViewModel::toLegacyGrid(int columns,int rows) const
{
    if(columns<=0||rows<=0||layout_.devices().empty()||!layout_.validate().isValid())return std::nullopt;
    const auto& devices=layout_.devices();int root=-1;for(int i=0;i<int(devices.size());++i)if(devices[i].uuid==localUuid_){root=i;break;}if(root<0)return std::nullopt;
    QVector<std::optional<QPoint>> positions(int(devices.size()));positions[root]=QPoint(0,0);bool changed=true;
    while(changed){changed=false;for(int i=0;i<int(devices.size());++i)if(positions[i])for(int j=0;j<int(devices.size());++j)if(i!=j&&!positions[j]){QPoint delta;bool adjacent=true;const QRect&a=devices[i].geometry,&b=devices[j].geometry;const bool yOverlap=qMax(a.top(),b.top())<=qMin(a.bottom(),b.bottom()),xOverlap=qMax(a.left(),b.left())<=qMin(a.right(),b.right());if(yOverlap&&a.right()+1==b.left())delta={1,0};else if(yOverlap&&b.right()+1==a.left())delta={-1,0};else if(xOverlap&&a.bottom()+1==b.top())delta={0,1};else if(xOverlap&&b.bottom()+1==a.top())delta={0,-1};else adjacent=false;if(adjacent){positions[j]=*positions[i]+delta;changed=true;}}}
    if(std::any_of(positions.begin(),positions.end(),[](const auto& value){return !value.has_value();}))return std::nullopt;
    int minX=0,maxX=0,minY=0,maxY=0;for(const auto&p:positions){minX=qMin(minX,p->x());maxX=qMax(maxX,p->x());minY=qMin(minY,p->y());maxY=qMax(maxY,p->y());}
    if(maxX-minX+1>columns||maxY-minY+1>rows)return std::nullopt;
    const int offsetX=std::clamp(columns/2-positions[root]->x(),-minX,columns-1-maxX),offsetY=std::clamp(rows/2-positions[root]->y(),-minY,rows-1-maxY);
    QStringList result(columns*rows,QString());for(int i=0;i<int(devices.size());++i){const QPoint cell=*positions[i]+QPoint(offsetX,offsetY);const int index=cell.y()*columns+cell.x();if(index<0||index>=result.size()||!result[index].isEmpty())return std::nullopt;result[index]=devices[i].technicalName;}
    return result;
}
ScreenLayoutEditorWidget::ScreenLayoutEditorWidget(QWidget* parent):QWidget(parent)
{
    setFocusPolicy(Qt::StrongFocus);setAccessibleName(tr("Editor visual de computadores"));setAccessibleDescription(tr("Organize até quatro computadores nas direções esquerda, direita, acima ou abaixo."));setMinimumHeight(250);
    simulationTimer_.setSingleShot(false);connect(&simulationTimer_,&QTimer::timeout,this,[this]{if(--remaining_<=0){simulationTimer_.stop();status_=tr("Simulação concluída. Nenhum ponteiro foi movido.");emit simulationFinished();}else status_=tr("Simulação: passagem em %1 s — Cancelar").arg(remaining_);update();});
}
void ScreenLayoutEditorWidget::setLayoutModel(const ScreenLayout& layout,const QUuid& localUuid){model_=ScreenLayoutEditorViewModel(layout.repaired(),localUuid);localUuid_=localUuid;selected_=localUuid;status_=tr("Arraste ou use Ctrl + setas para posicionar um computador.");update();}
void ScreenLayoutEditorWidget::setDevicePresentation(const QUuid& uuid,const QString& displayName,const QString& operatingSystem){if(displayName.trimmed().isEmpty())displayNames_.remove(uuid);else displayNames_[uuid]=displayName.trimmed();if(operatingSystem.trimmed().isEmpty())operatingSystems_.remove(uuid);else operatingSystems_[uuid]=operatingSystem.trimmed();update();}
int ScreenLayoutEditorWidget::visibleDeviceCount() const{return qMin(5,static_cast<int>(model_.layout().devices().size()));}
QString ScreenLayoutEditorWidget::monitorSummaryForTest(const QUuid& uuid) const{const auto*d=model_.device(uuid);if(!d)return {};const int count=qMax(1,static_cast<int>(d->monitors.size()));return count==1?tr("1 monitor"):tr("%1 monitores").arg(count);}
QString ScreenLayoutEditorWidget::cardAccessibleDescriptionForTest(const QUuid& uuid) const{const auto*d=model_.device(uuid);if(!d)return {};return tr("Computador %1, %2").arg(displayNames_.value(uuid,d->technicalName),monitorSummaryForTest(uuid));}
void ScreenLayoutEditorWidget::setTechnicalAdjustmentsVisible(bool visible){technicalVisible_=visible;status_=visible?tr("Ajustes técnicos e grade antiga visíveis."):tr("Modo simples: apenas computadores configurados.");update();}
QString ScreenLayoutEditorWidget::directionText(ScreenLayoutEditorViewModel::Direction d){switch(d){case ScreenLayoutEditorViewModel::Direction::Left:return tr("À esquerda");case ScreenLayoutEditorViewModel::Direction::Right:return tr("À direita");case ScreenLayoutEditorViewModel::Direction::Above:return tr("Acima");case ScreenLayoutEditorViewModel::Direction::Below:return tr("Abaixo");}return {};}
void ScreenLayoutEditorWidget::previewDrop(const QUuid&,const QUuid&,ScreenLayoutEditorViewModel::Direction d){status_=tr("%1 — solte para encaixar").arg(directionText(d));emit dropTargetChanged(status_);update();}
void ScreenLayoutEditorWidget::startPassageSimulation(){remaining_=5;status_=tr("Simulação: passagem em 5 s — Cancelar");simulationTimer_.start(interval_);update();}
void ScreenLayoutEditorWidget::cancelPassageSimulation(){simulationTimer_.stop();remaining_=0;status_=tr("Simulação cancelada. Nenhum ponteiro foi movido.");update();}
void ScreenLayoutEditorWidget::keyPressEvent(QKeyEvent* e){if((e->modifiers()&Qt::ControlModifier)&&!selected_.isNull()){auto d=ScreenLayoutEditorViewModel::Direction::Left;if(e->key()==Qt::Key_Right)d=ScreenLayoutEditorViewModel::Direction::Right;else if(e->key()==Qt::Key_Up)d=ScreenLayoutEditorViewModel::Direction::Above;else if(e->key()==Qt::Key_Down)d=ScreenLayoutEditorViewModel::Direction::Below;else return QWidget::keyPressEvent(e);if(model_.moveAdjacent(selected_,localUuid_,d)){status_=tr("Posicionado: %1").arg(directionText(d));emit layoutChanged();}else status_=tr("Não foi possível posicionar aqui: o espaço já está ocupado.");update();return;}QWidget::keyPressEvent(e);}
void ScreenLayoutEditorWidget::mousePressEvent(QMouseEvent* event){if(event->button()!=Qt::LeftButton)return QWidget::mousePressEvent(event);for(auto it=cardRects_.cbegin();it!=cardRects_.cend();++it)if(it.value().contains(event->position())){selected_=dragged_=it.key();dragStart_=event->position().toPoint();dragging_=false;hasDropTarget_=false;setFocus();update();event->accept();return;}QWidget::mousePressEvent(event);}
void ScreenLayoutEditorWidget::updateDropTarget(const QPoint& position){qreal best=std::numeric_limits<qreal>::max();dropAnchor_={};for(auto it=cardRects_.cbegin();it!=cardRects_.cend();++it){if(it.key()==dragged_)continue;const QPointF delta=position-it.value().center();const qreal distance=delta.x()*delta.x()+delta.y()*delta.y();if(distance<best){best=distance;dropAnchor_=it.key();dropDirection_=qAbs(delta.x())>=qAbs(delta.y())?(delta.x()<0?ScreenLayoutEditorViewModel::Direction::Left:ScreenLayoutEditorViewModel::Direction::Right):(delta.y()<0?ScreenLayoutEditorViewModel::Direction::Above:ScreenLayoutEditorViewModel::Direction::Below);}}hasDropTarget_=!dropAnchor_.isNull();if(hasDropTarget_){const QRectF area=cardRects_.value(dropAnchor_);const qreal limit=qMax(area.width(),area.height())*1.25;hasDropTarget_=best<=limit*limit;}if(hasDropTarget_)previewDrop(dragged_,dropAnchor_,dropDirection_);}
void ScreenLayoutEditorWidget::mouseMoveEvent(QMouseEvent* event){if(dragged_.isNull()||!(event->buttons()&Qt::LeftButton))return QWidget::mouseMoveEvent(event);if(!dragging_&&(event->position().toPoint()-dragStart_).manhattanLength()<QApplication::startDragDistance())return;dragging_=true;updateDropTarget(event->position().toPoint());event->accept();}
void ScreenLayoutEditorWidget::mouseReleaseEvent(QMouseEvent* event){if(event->button()==Qt::LeftButton&&dragging_&&hasDropTarget_){if(model_.moveAdjacent(dragged_,dropAnchor_,dropDirection_)){status_=tr("Posicionado: %1").arg(directionText(dropDirection_));emit layoutChanged();}else status_=tr("Não foi possível posicionar aqui: o espaço já está ocupado.");event->accept();}dragged_={};dropAnchor_={};dragging_=false;hasDropTarget_=false;update();if(!event->isAccepted())QWidget::mouseReleaseEvent(event);}
void ScreenLayoutEditorWidget::paintEvent(QPaintEvent*){QPainter p(this);p.setRenderHint(QPainter::Antialiasing);p.fillRect(rect(),QColor("#f8fafc"));const auto& devices=model_.layout().devices();cardRects_.clear();if(devices.empty()){p.setPen(QColor("#64748b"));p.drawText(rect(),Qt::AlignCenter,tr("Nenhum computador configurado"));return;}QList<const ScreenLayout::Device*> shown;auto local=std::find_if(devices.begin(),devices.end(),[&](const auto& d){return d.uuid==localUuid_;});if(local!=devices.end())shown.append(&*local);for(const auto& d:devices)if(d.uuid!=localUuid_&&shown.size()<5)shown.append(&d);QRect bounds;for(const auto* d:shown)bounds=bounds.united(d->geometry);const qreal scale=qMin((width()-80.0)/qMax(1,bounds.width()),(height()-90.0)/qMax(1,bounds.height()));for(const auto* d:shown){QRectF r((d->geometry.x()-bounds.x())*scale+40,(d->geometry.y()-bounds.y())*scale+25,d->geometry.width()*scale-8,d->geometry.height()*scale-8);cardRects_.insert(d->uuid,r);p.setBrush(d->uuid==selected_?QColor("#dbeafe"):Qt::white);p.setPen(QPen(d->uuid==selected_?QColor("#2563eb"):QColor("#94a3b8"),2));p.drawRoundedRect(r,10,10);if(hasDropTarget_&&d->uuid==dropAnchor_){p.setBrush(QColor(37,99,235,45));p.setPen(QPen(QColor("#2563eb"),2,Qt::DashLine));p.drawRoundedRect(r.adjusted(4,4,-4,-4),8,8);}p.setPen(QColor("#0f172a"));QString text=displayNames_.value(d->uuid,d->technicalName);const QString os=operatingSystems_.value(d->uuid);if(!os.isEmpty())text+=QString("\n%1").arg(os);if(d->uuid==localUuid_)text+=tr("\nEste computador");text+=QString("\n%1").arg(monitorSummaryForTest(d->uuid));p.drawText(r.adjusted(8,8,-8,-8),Qt::AlignCenter|Qt::TextWordWrap,text);}p.setPen(QColor("#475569"));const QString footer=devices.size()>5?tr("%1 • Outros computadores estão nos ajustes técnicos").arg(status_):status_;p.drawText(QRect(8,height()-35,width()-16,30),Qt::AlignCenter,footer);}
