[package]
name = "input-leap-server"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"
publish = false
rust-version = "1.88"

[dependencies]
inputleap-protocol-legacy = { path = "../../crates/inputleap-protocol-legacy", version = "0.1.0" }
inputleap-runtime = { path = "../../crates/inputleap-runtime", version = "0.1.0" }
inputleap-platform-windows = { path = "../../crates/inputleap-platform-windows", version = "0.1.0" }

[workspace]
