@echo off
setlocal EnableExtensions
for %%I in ("%~dp0..\..") do set "REPO_ROOT=%%~fI"
pushd "%REPO_ROOT%" || exit /b 1

set "BUILD_DIR=%REPO_ROOT%\out\build\windows-msvc-tests"
set "INTEROP_DIR=%BUILD_DIR%\rust-r2-cnop-interop"
set "CPP_EXE=%INTEROP_DIR%\rust-r2-cnop-interop.exe"
set "FIXTURE=%REPO_ROOT%\rust\crates\inputleap-protocol-legacy\tests\fixtures\remote-cnop-payload.bin"
set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"

if not exist "%VSWHERE%" goto :missing_toolchain
for /f "usebackq tokens=*" %%I in (`"%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VS_INSTALL=%%I"
if not defined VS_INSTALL goto :missing_toolchain
call "%VS_INSTALL%\VC\Auxiliary\Build\vcvars64.bat" >nul
if errorlevel 1 goto :failed

if not exist "%BUILD_DIR%\CMakeCache.txt" goto :missing_build
cmake --build "%BUILD_DIR%" --target protocol-fixture-emitter -j 2
if errorlevel 1 goto :failed

for %%L in (
  "%BUILD_DIR%\src\lib\inputleap\synlib.lib"
  "%BUILD_DIR%\src\lib\base\base.lib"
  "%BUILD_DIR%\src\lib\io\io.lib"
  "%BUILD_DIR%\src\lib\common\common.lib"
  "%BUILD_DIR%\src\lib\arch\arch.lib"
  "%BUILD_DIR%\src\lib\ipc\ipc.lib"
) do if not exist "%%~L" goto :missing_library

if not exist "%INTEROP_DIR%" mkdir "%INTEROP_DIR%"
cl /nologo /EHsc /std:c++20 /MDd /W4 /permissive- /wd4100 /DSYSAPI_WIN32=1 /DWIN32 /D_WINDOWS /DWINAPI_MSWINDOWS=1 /D_CRT_SECURE_NO_WARNINGS /I"%REPO_ROOT%\src\lib" /I"%BUILD_DIR%\src\lib" "%REPO_ROOT%\src\test\rust-r2\CnopInterop.cpp" /Fo"%INTEROP_DIR%\CnopInterop.obj" /Fe"%CPP_EXE%" "%BUILD_DIR%\src\lib\inputleap\synlib.lib" "%BUILD_DIR%\src\lib\base\base.lib" "%BUILD_DIR%\src\lib\io\io.lib" "%BUILD_DIR%\src\lib\common\common.lib" "%BUILD_DIR%\src\lib\arch\arch.lib" "%BUILD_DIR%\src\lib\ipc\ipc.lib" "%REPO_ROOT%\deps\vcpkg\installed\x64-windows-static\debug\lib\libcrypto.lib" crypt32.lib ws2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /link /machine:x64 /pdb:"%INTEROP_DIR%\rust-r2-cnop-interop.pdb"
if errorlevel 1 goto :failed

if /I "%~1"=="fixture" goto :fixture
if not "%~1"=="" goto :usage
if not exist "%FIXTURE%" goto :missing_fixture

set "CPP_BYTES=%INTEROP_DIR%\cpp-encoded.bin"
set "RUST_BYTES=%INTEROP_DIR%\rust-encoded.bin"
"%CPP_EXE%" emit "%CPP_BYTES%"
if errorlevel 1 goto :failed
cargo run --locked --manifest-path "%REPO_ROOT%\rust\Cargo.toml" --package inputleap-protocol-legacy --example cnop_interop -- decode "%CPP_BYTES%" client-to-server active
if errorlevel 1 goto :failed
cargo run --locked --manifest-path "%REPO_ROOT%\rust\Cargo.toml" --package inputleap-protocol-legacy --example cnop_interop -- encode "%RUST_BYTES%" client-to-server active
if errorlevel 1 goto :failed
"%CPP_EXE%" decode "%RUST_BYTES%"
if errorlevel 1 goto :failed
fc /b "%CPP_BYTES%" "%RUST_BYTES%" >nul
if errorlevel 1 goto :byte_mismatch
fc /b "%FIXTURE%" "%CPP_BYTES%" >nul
if errorlevel 1 goto :fixture_mismatch
set "TRAILING_BYTES=%INTEROP_DIR%\cnop-with-trailing.bin"
copy /b "%CPP_BYTES%"+"%CPP_BYTES%" "%TRAILING_BYTES%" >nul
if errorlevel 1 goto :failed
"%CPP_EXE%" decode "%TRAILING_BYTES%" >nul 2>&1
if not errorlevel 1 goto :decoder_false_accept
cargo run --quiet --locked --manifest-path "%REPO_ROOT%\rust\Cargo.toml" --package inputleap-protocol-legacy --example cnop_interop -- decode "%TRAILING_BYTES%" client-to-server active >nul 2>&1
if not errorlevel 1 goto :decoder_false_accept
del /q "%TRAILING_BYTES%"
python "%REPO_ROOT%\.hermes\scripts\generate-rust-r0-source-manifest.py" --check
if errorlevel 1 goto :failed
echo RUST_R2_CNOP_INTEROP_PASS byte_cpp_to_rust=PASS byte_rust_to_cpp=PASS bytes_equal=PASS fixture_equal=PASS strict_file_trailing_rejected=PASS r0=PASS
popd
exit /b 0

:fixture
if not "%~3"=="" goto :usage
if "%~2"=="" goto :usage
set "FIXTURE_OUTPUT=%~f2"
if exist "%FIXTURE_OUTPUT%" goto :output_exists
"%CPP_EXE%" emit "%FIXTURE_OUTPUT%"
if errorlevel 1 goto :failed
certutil -hashfile "%FIXTURE_OUTPUT%" SHA256
if errorlevel 1 goto :failed
popd
exit /b 0

:missing_toolchain
echo rust-r2-cnop-interop: Visual Studio C++ toolchain not found 1>&2
popd
exit /b 2

:missing_build
echo rust-r2-cnop-interop: expected existing build tree at "%BUILD_DIR%" 1>&2
popd
exit /b 2

:missing_library
echo rust-r2-cnop-interop: required existing C++ library is missing: %%~L 1>&2
popd
exit /b 2

:missing_fixture
echo rust-r2-cnop-interop: frozen fixture is missing: "%FIXTURE%" 1>&2
popd
exit /b 2

:byte_mismatch
echo rust-r2-cnop-interop: C++ and Rust encoded bytes differ 1>&2
popd
exit /b 1

:fixture_mismatch
echo rust-r2-cnop-interop: generated bytes differ from frozen C++ fixture 1>&2
popd
exit /b 1

:decoder_false_accept
echo rust-r2-cnop-interop: C++ or Rust decoder accepted trailing bytes 1>&2
del /q "%TRAILING_BYTES%" >nul 2>&1
popd
exit /b 1

:output_exists
echo rust-r2-cnop-interop: refusing to overwrite existing fixture candidate: "%FIXTURE_OUTPUT%" 1>&2
popd
exit /b 2

:usage
echo usage: rust-r2-cnop-interop.bat [fixture ^<new-output-path^>] 1>&2
popd
exit /b 2

:failed
set "RESULT=%ERRORLEVEL%"
popd
exit /b %RESULT%
